#BSUB -n 1
#BSUB -M 20000
#BSUB -W 50:00
# execute program
cd /data/weirauchlab/team/ches2d/OngoingProjects/Meenakshi_enrichment_analysis_Jan2018/Round1/Exons/SRSF2-P95
/data/weirauchlab/web/bin/bedsig_LDextension_new input rip-validation-RBP	HT-1080	ELAVL1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input rip-validation-RBP	HT-1080	IGF2BP1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	293S	AGO2+arsenite  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	293S	AGO2+emetine  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	293S	AGO2+hippuristanol  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	293S	AGO2+no_arsenite  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	293S	AGO2+no_emetine  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	293S	AGO2+no_hippuristanol  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	BC-1	AGO2+KSHV-infected  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	BC-3	AGO2+KSHV-infected  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	BC-3	AGO2+KSHV-infected_4thiouridine  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	BCBL-1	AGO2+KSHV-infected  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	Brain_temporal_cortices	FUS+Rnase_T1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	brain_tissue	TDP-43  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	EF3D-AGO2	AGO2+EBV_B95-8-infected_4thiouridine  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	H9-hESC	AGO2+4-thiouridine_RNaseT1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	H9-hESC	LIN28  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	HEK293	AGO1+4-thiouridine_ML_MM_6  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	HEK293	AGO1+4-thiouridine_ML_MM_7  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	HEK293	AGO1+4-thiouridine_ML_MM_8  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	HEK293	AGO1+4-thiouridine_RNaseT1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	HEK293	AGO2+4-thiouridine_3_ML_LG  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	HEK293	AGO2+4-thiouridine_RNaseT1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	HEK293	AGO2+completeT1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	HEK293	AGO2+mildMNase  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	HEK293	AGO2+miR-124_transfected  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	HEK293	AGO2+miR-7_transfected  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	HEK293	AGO3+4-thiouridine_RNaseT1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	HEK293	AGO4+4-thiouridine_RNaseT1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	HEK293	ALKBH5+4-thiouridine  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	HEK293	C17ORF85+4-thiouridine  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	HEK293	C22ORF28+4-thiouridine  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	HEK293	CAPRIN1+4-thiouridine  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	HEK293	EWSR1+4-thiouridine  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	HEK293	FMRP+I304N_mutant_iso1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	HEK293	FMRP+I304N_mutant_iso7  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	HEK293	FMRP+WT_iso1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	HEK293	FMRP+WT_iso7  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	HEK293	FUS+4-thiouridine  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	HEK293	FUS-mutant+4-thiouridine  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	HEK293	FXR1+WT_4thiouridine  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	HEK293	FXR2+WT_4thiouridine  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	HEK293	HuR+completeT1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	HEK293	HuR+mildMNase  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	HEK293	IGF2BP1+doxycycline_induced  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	HEK293	IGF2BP2+doxycycline_induced  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	HEK293	IGF2BP3+doxycycline_induced  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	HEK293	LIN28  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	HEK293	LIN28A+4-thiouridine_RnaseT1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	HEK293	LIN28B+4-thiouridine_RnaseT1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	HEK293	MOV10+4-thiouridine  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	HEK293	PUM2+4-thiouridine_RnaseT1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	HEK293	QKI+4-thiouridine_RnaseT1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	HEK293	TAF15+4-thiouridine  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	HEK293	TNRC6+doxycycline_induced_+4-thiouridine_RNaseT1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	HEK293	ZC3H7B+4-thiouridine  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	HEK293T	DGCR8+D8  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	HEK293T	DGCR8+T7  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	HEK293T	SFRS1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	Hela	AGO2+control_shRNA  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	Hela	AGO2+PTB_specific_shRNA  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	Hela	eIF4AIII+RNaseT1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	Hela	hnRNPC  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	Hela	PTB  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	Hela	TIA1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	Hela	TIAL1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	Hela	U2AF65+control_siRNA  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	Hela	UPF1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	Hela	UPF1+puromycoin  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	Jijoye	AGO2+EBV-infected  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	LCL35	AGO2+EBV_B95-8-infected_4-thiouridine_RNaseT1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	LCL-BAC	AGO2+EBV_B95-8-infected_4-thiouridine_RNaseT1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	LCL-BACD1	AGO2+EBV_B95-8-infected_4-thiouridine_RNaseT1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input starbase_database-RBP	LCL-BACD3	AGO2+EBV_B95-8-infected_4-thiouridine_RNaseT1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	cardiomyocytes	RBM20  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HEK293	RBM20  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	immortalized_cell_line	U2AF1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	MEF_cells	SRSF2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HeLa	SF3B1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	293T	WTAP  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	AARS  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	AARS  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	AGGF1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	AGGF1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	AGGF1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	AGGF1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	AKAP8L  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	AKAP8L  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	AUH  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	AUH  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	AUH  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	AUH  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	BCCIP  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	BCCIP  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	BUD13  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	BUD13  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	BUD13  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	BUD13  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	CDC40  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	CDC40  -null RefGene_Exons -boncorr 500 
