#BSUB -n 1
#BSUB -M 20000
#BSUB -W 50:00
# execute program
cd /data/weirauchlab/team/ches2d/OngoingProjects/Meenakshi_enrichment_analysis_Jan2018/Round1/Exons/SRSF2-P95
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	CPSF6  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	CPSF6  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	CSTF2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	CSTF2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	CSTF2T  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	CSTF2T  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	CSTF2T  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	CSTF2T  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	DDX24  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	DDX24  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	DDX3X  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	DDX3X  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	DDX3X  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	DDX3X  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	DDX42  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	DDX42  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	DDX55  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	DDX55  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	DDX55  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	DDX55  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	DDX59  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	DDX59  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	DDX6  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	DDX6  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	DDX6  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	DDX6  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	AdrenalGland@1	DGCR8  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	AdrenalGland@2	DGCR8  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	DGCR8  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	DGCR8  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	DHX30  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	DHX30  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	DHX30  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	DHX30  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	DKC1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	DKC1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	DROSHA  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	DROSHA  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	EFTUD2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	EFTUD2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	EFTUD2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	EFTUD2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	EIF3D  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	EIF3D  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	EIF4G2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	EIF4G2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	EWSR1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	EWSR1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	FAM120A  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	FAM120A  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	FAM120A  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	FAM120A  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	FASTKD2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	FASTKD2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	FASTKD2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	FASTKD2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	FKBP4  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	FKBP4  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	FMR1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	FMR1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	FTO  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	FTO  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	FUBP3  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	FUBP3  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	FXR1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	FXR1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	FXR2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	FXR2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	GEMIN5  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	GEMIN5  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	GNL3  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	GNL3  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	GPKOW  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	GPKOW  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	GRSF1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	GRSF1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	GRWD1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	GRWD1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	GTF2F1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	GTF2F1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	GTF2F1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	GTF2F1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	HLTF  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	HLTF  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	HNRNPA1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	HNRNPA1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	HNRNPA1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	HNRNPA1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	HNRNPC  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	HNRNPC  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	HNRNPK  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	HNRNPK  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	HNRNPK  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	HNRNPK  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	HNRNPM  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	HNRNPM  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	HNRNPM  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	HNRNPM  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	HNRNPU  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	HNRNPU  -null RefGene_Exons -boncorr 500 
