#BSUB -n 1
#BSUB -M 20000
#BSUB -W 50:00
# execute program
cd /data/weirauchlab/team/ches2d/OngoingProjects/Meenakshi_enrichment_analysis_Jan2018/Round1/Exons/SRSF2-P95
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	HNRNPU  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	HNRNPU  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	HNRNPUL1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	HNRNPUL1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	HNRNPUL1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	HNRNPUL1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	IGF2BP1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	IGF2BP1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	IGF2BP1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	IGF2BP1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	IGF2BP2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	IGF2BP2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	IGF2BP3  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	IGF2BP3  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	ILF3  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	ILF3  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	ILF3  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	ILF3  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	KHDRBS1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	KHDRBS1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	KHSRP  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	KHSRP  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	LARP4  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	LARP4  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	LARP4  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	LARP4  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	LARP7  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	LARP7  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	LARP7  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	LARP7  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	LIN28B  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	LIN28B  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	LIN28B  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	LIN28B  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	LSM11  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	LSM11  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	LSM11  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	LSM11  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	METAP2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	METAP2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	MTPAP  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	MTPAP  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	NCBP2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	NCBP2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	NCBP2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	NCBP2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	NKRF  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	NKRF  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	NOL12  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	NOL12  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	NONO  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	NONO  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	NPM1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	NPM1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	NSUN2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	NSUN2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	PCBP2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	PCBP2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	PPIG  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	PPIG  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	PPIL4  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	PPIL4  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	PRPF8  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	PRPF8  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	PRPF8  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	PRPF8  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	PTBP1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	PTBP1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	PTBP1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	PTBP1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	PUM2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	PUM2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	PUS1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	PUS1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	QKI  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	QKI  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	QKI  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	QKI  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	RBFOX2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	RBFOX2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	RBFOX2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	RBFOX2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	RBM15  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	RBM15  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	RBM15  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	RBM15  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	RBM22  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	RBM22  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	RBM22  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	RBM22  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	RBM27  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	RBM27  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	RPS11  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	RPS11  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	RPS5  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	RPS5  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	RPS5  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	RPS5  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	SAFB2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	SAFB2  -null RefGene_Exons -boncorr 500 
