#BSUB -n 1
#BSUB -M 20000
#BSUB -W 50:00
# execute program
cd /data/weirauchlab/team/ches2d/OngoingProjects/Meenakshi_enrichment_analysis_Jan2018/Round1/Exons/HNRNPK-KD_variants
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	BC-1	AGO2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	BC-3	AGO2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	BCBL-1	AGO2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	EF3D-AGO2	AGO2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	H9	LIN28A  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	H9	TARDBP  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	HCT116	EZH2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	HEK293	AGO1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	HEK293	AGO2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	HEK293	AGO3  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	HEK293	AGO4  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	HEK293	ALKBH5  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	HEK293	C17orf85  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	HEK293	CAPRIN1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	HEK293	CPSF1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	HEK293	CPSF2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	HEK293	CPSF3  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	HEK293	CPSF4  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	HEK293	CPSF6  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	HEK293	CPSF7  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	HEK293	CSTF2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	HEK293	CSTF2T  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	HEK293	ELAVL1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	HEK293	FBL  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	HEK293	FIP1L1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	HEK293	FMR1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	HEK293	FXR1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	HEK293	FXR2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	HEK293	IGF2BP1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	HEK293	IGF2BP2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	HEK293	IGF2BP3  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	HEK293	LIN28A  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	HEK293	LIN28B  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	HEK293	MOV10  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	HEK293	NOP56  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	HEK293	NOP58  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	HEK293	NUDT21  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	HEK293	PUM2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	HEK293	QKI  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	HEK293	RTCB  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	HEK293	TNRC6A  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	HEK293	TNRC6B  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	HEK293	TNRC6C  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	HEK293	ZC3H7B  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	HEK293S	AGO2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	HEK293T	ATXN2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	HEK293T	DGCR8  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	HEK293T	FUS  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	HEK293T	HNRNPA1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	HEK293T	HNRNPA2B1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	HEK293T	HNRNPF  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	HEK293T	HNRNPH  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	HEK293T	HNRNPM  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	HEK293T	HNRNPU  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	HEK293T	TARDBP  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	HeLa	AGO2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	HeLa	CSTF2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	HeLa	EIF4A3  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	HeLa	ELAVL1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	HeLa	HNRNPC  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	HeLa	HNRNPU  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	HeLa	PTBP1PTBP2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	HeLa	TIA1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	HeLa	TIAL1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	HeLa	YTHDF2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	LCL35	AGO2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	LCL-BAC	AGO2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	LCL-BAC-D1	AGO2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	LCL-BAC-D2	AGO2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	LCL-BAC-D3	AGO2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input CLIPdb-RBP	SH-SY5Y	TARDBP  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input rip-gene_st-RBP	GM12878	CELF1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input rip-gene_st-RBP	GM12878	ELAVL1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input rip-gene_st-RBP	GM12878	IGF2BP1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input rip-gene_st-RBP	GM12878	PABPC1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input rip-gene_st-RBP	GM12878	SLBP  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input rip-gene_st-RBP	GM12878	T7Tag  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input rip-gene_st-RBP	H1-hESC	ELAVL1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input rip-gene_st-RBP	H1-hESC	T7Tag  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input rip-gene_st-RBP	HeLa-S3	ELAVL1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input rip-gene_st-RBP	HeLa-S3	PABPC1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input rip-gene_st-RBP	HeLa-S3	T7Tag  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input rip-gene_st-RBP	HepG2	ELAVL1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input rip-gene_st-RBP	HepG2	PABPC1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input rip-gene_st-RBP	HepG2	T7Tag  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input rip-gene_st-RBP	K562	CELF1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input rip-gene_st-RBP	K562	ELAVL1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input rip-gene_st-RBP	K562	PABPC1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input rip-gene_st-RBP	K562	SLBP  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input rip-gene_st-RBP	K562	T7Tag  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input rip-seq-RBP	GM12878	ELAVL1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input rip-seq-RBP	GM12878	PABPC1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input rip-seq-RBP	K562	ELAVL1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input rip-seq-RBP	K562	PABPC1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input rip-tiling_array-RBP	GM12878	ELAVL1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input rip-tiling_array-RBP	GM12878	PABPC1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input rip-tiling_array-RBP	GM12878	T7Tag  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input rip-tiling_array-RBP	K562	ELAVL1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input rip-tiling_array-RBP	K562	PABPC1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input rip-tiling_array-RBP	K562	T7Tag  -null RefGene_Exons -boncorr 500 
