#BSUB -n 1
#BSUB -M 20000
#BSUB -W 50:00
# execute program
cd /data/weirauchlab/team/ches2d/OngoingProjects/Meenakshi_enrichment_analysis_Jan2018/Round1/Exons/HNRNPK-KD_variants
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	SBDS  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	SBDS  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	SERBP1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	SERBP1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	SF3A3  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	SF3A3  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	SF3B1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	SF3B1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	SF3B4  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	SF3B4  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	SF3B4  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	SF3B4  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	SFPQ  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	SFPQ  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	SLBP  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	SLBP  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	SLTM  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	SLTM  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	SLTM  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	SLTM  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	SMNDC1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	SMNDC1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	SMNDC1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	SMNDC1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	SND1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	SND1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	SND1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	SND1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	SRSF1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	SRSF1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	SRSF1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	SRSF1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	SRSF7  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	SRSF7  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	SRSF7  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	SRSF7  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	SRSF9  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	SRSF9  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	SUB1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	SUB1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	SUGP2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	SUGP2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	SUPV3L1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	SUPV3L1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	TAF15  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	TAF15  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	TAF15  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	TAF15  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	TARDBP  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	TARDBP  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	TBRG4  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	TBRG4  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	TBRG4  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	TBRG4  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	TIA1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	TIA1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	TIA1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	TIA1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	TNRC6A  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	TNRC6A  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	TRA2A  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	TRA2A  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	TRA2A  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	TRA2A  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	TROVE2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	TROVE2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	TROVE2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	TROVE2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	U2AF1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	U2AF1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	U2AF1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	U2AF1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	U2AF2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	U2AF2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	U2AF2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	U2AF2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	UCHL5  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	UCHL5  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	UCHL5  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	UCHL5  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	UPF1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	UPF1  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	XPO5  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	XPO5  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	XRCC6  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	XRCC6  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	XRCC6  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	XRCC6  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@1	XRN2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	HepG2@2	XRN2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	XRN2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	XRN2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	YBX3  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	YBX3  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	YWHAG  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	YWHAG  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	ZNF622  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	ZNF622  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@1	ZRANB2  -null RefGene_Exons -boncorr 500 
/data/weirauchlab/web/bin/bedsig_LDextension_new input Misc_Clip-seq	K562@2	ZRANB2  -null RefGene_Exons -boncorr 500 
